CREATE ROLE GIFTREG_ROLE;

CREATE USER GIFTREG_SCHEMA IDENTIFIED BY "f5vf8wFSrgkalk0"
	DEFAULT TABLESPACE GIFTREG_DTS
	TEMPORARY TABLESPACE GIFTREG_TEMP
	QUOTA UNLIMITED ON GIFTREG_DTS
	ACCOUNT LOCK
/
GRANT RESOURCE TO GIFTREG_SCHEMA
/

CREATE USER GIFTREG_APP IDENTIFIED BY "s0mepassw0rd"
	DEFAULT TABLESPACE GIFTREG_USERS
	TEMPORARY TABLESPACE GIFTREG_TEMP
	ACCOUNT UNLOCK
/
GRANT CONNECT TO GIFTREG_APP
/
