CREATE TABLE GIFTREG_TEST_SCHEMA.GIFT (
  GIFT_ID             NUMBER          NOT NULL,
  SHORT_DESC          VARCHAR2(1024)  NOT NULL,
  LONG_DESC           VARCHAR2(4000)  NULL,
  LOCATION            VARCHAR2(1024)  NULL,
  WANTED_BY_PERSON_ID NUMBER          NOT NULL,
  BOUGHT_BY_PERSON_ID NUMBER          NULL,
  PRIORITY_NBR        NUMBER          NOT NULL
)
TABLESPACE GIFTREG_TEST_DTS
/

CREATE UNIQUE INDEX GIFTREG_TEST_SCHEMA.GIFT_IX01 ON GIFTREG_TEST_SCHEMA.GIFT(GIFT_ID)
TABLESPACE GIFTREG_TEST_ITS
/

ALTER TABLE GIFTREG_TEST_SCHEMA.GIFT
ADD CONSTRAINT GIFT_PK PRIMARY KEY (GIFT_ID)
USING INDEX GIFTREG_TEST_SCHEMA.GIFT_IX01
/

CREATE SEQUENCE GIFTREG_TEST_SCHEMA.GIFT_ID_SEQ
START WITH 100
INCREMENT BY 1
/

CREATE TRIGGER GIFTREG_TEST_SCHEMA.GIFT_TRIG
BEFORE INSERT ON GIFTREG_TEST_SCHEMA.GIFT
FOR EACH ROW
BEGIN
  IF (:NEW.GIFT_ID IS NULL) THEN
    SELECT GIFTREG_TEST_SCHEMA.GIFT_ID_SEQ.NEXTVAL
    INTO :NEW.GIFT_ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE GIFTREG_TEST_SCHEMA.PERSON (
  PERSON_ID         NUMBER          NOT NULL,
  EMAIL_ADDRESS     VARCHAR2(100)   NOT NULL,
  PASSWORD          VARCHAR2(100)   NOT NULL,
  LAST_UPDATE_DT    NUMBER          NULL
)
TABLESPACE GIFTREG_TEST_DTS
/

CREATE UNIQUE INDEX GIFTREG_TEST_SCHEMA.PERSON_IX01 ON GIFTREG_TEST_SCHEMA.PERSON(PERSON_ID)
TABLESPACE GIFTREG_TEST_ITS
/

CREATE UNIQUE INDEX GIFTREG_TEST_SCHEMA.PERSON_IX02 ON GIFTREG_TEST_SCHEMA.PERSON(EMAIL_ADDRESS)
TABLESPACE GIFTREG_TEST_ITS
/

ALTER TABLE GIFTREG_TEST_SCHEMA.PERSON
ADD CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID)
USING INDEX GIFTREG_TEST_SCHEMA.PERSON_IX01
/

CREATE SEQUENCE GIFTREG_TEST_SCHEMA.PERSON_ID_SEQ
START WITH 100
INCREMENT BY 1
/

CREATE TRIGGER GIFTREG_TEST_SCHEMA.PERSON_TRIG
BEFORE INSERT ON GIFTREG_TEST_SCHEMA.PERSON
FOR EACH ROW
BEGIN
  IF (:NEW.PERSON_ID IS NULL) THEN
    SELECT GIFTREG_TEST_SCHEMA.PERSON_ID_SEQ.NEXTVAL
    INTO :NEW.PERSON_ID FROM DUAL;
  END IF;
END;
/

CREATE TABLE GIFTREG_TEST_SCHEMA.PASSWORD_RESET (
  PERSON_ID         NUMBER          NOT NULL,
  SECRET            VARCHAR2(100)   NOT NULL,
  EXPIRE_DT         NUMBER          NOT NULL
)
TABLESPACE GIFTREG_TEST_DTS
/

ALTER TABLE GIFTREG_TEST_SCHEMA.PASSWORD_RESET
ADD CONSTRAINT SECRET_UNIQUE UNIQUE (SECRET)
/

