GRANT ALL ON GIFTREG_SCHEMA.GIFT TO GIFTREG_ROLE
/
GRANT ALL ON GIFTREG_SCHEMA.PERSON TO GIFTREG_ROLE
/
GRANT ALL ON GIFTREG_SCHEMA.PASSWORD_RESET TO GIFTREG_ROLE
/
GRANT ALL ON GIFTREG_SCHEMA.GIFT_ID_SEQ TO GIFTREG_ROLE
/
GRANT ALL ON GIFTREG_SCHEMA.PERSON_ID_SEQ TO GIFTREG_ROLE
/
GRANT GIFTREG_ROLE TO GIFTREG_APP
/
