CREATE TABLESPACE GIFTREG_TEST_DTS
	DATAFILE SIZE 100M AUTOEXTEND OFF
/

CREATE TABLESPACE GIFTREG_TEST_ITS
	DATAFILE SIZE 10M AUTOEXTEND OFF
/

CREATE TABLESPACE GIFTREG_TEST_USERS
	DATAFILE SIZE 10M AUTOEXTEND OFF
/

CREATE TEMPORARY TABLESPACE GIFTREG_TEST_TEMP
	TEMPFILE SIZE 10M AUTOEXTEND OFF
/
