GRANT ALL ON GIFTREG_TEST_SCHEMA.GIFT TO GIFTREG_TEST_ROLE
/
GRANT ALL ON GIFTREG_TEST_SCHEMA.PERSON TO GIFTREG_TEST_ROLE
/
GRANT ALL ON GIFTREG_TEST_SCHEMA.PASSWORD_RESET TO GIFTREG_TEST_ROLE
/
GRANT ALL ON GIFTREG_TEST_SCHEMA.GIFT_ID_SEQ TO GIFTREG_TEST_ROLE
/
GRANT ALL ON GIFTREG_TEST_SCHEMA.PERSON_ID_SEQ TO GIFTREG_TEST_ROLE
/
GRANT GIFTREG_TEST_ROLE TO GIFTREG_TEST_APP
/
