#!/usr/bin/env perl
use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

# For DBD::Oracle
$ENV{LD_LIBRARY_PATH} .= ':/opt/oracle/instantclient_11_2';
$ENV{TNS_ADMIN} = '/opt/oracle/instantclient_11_2';

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Application
$ENV{MOJO_APP} ||= 'Giftreg';

# Start commands
Mojolicious::Commands->start_app($ENV{MOJO_APP});
